GET http://localhost:3000/timetable

###

GET http://localhost:3000/timetable/CS/B/5

###

GET http://localhost:3000/timetable/Monday

###

POST http://localhost:3000/timetable/
Content-Type: application/json

{
    "subject": "Microprocessor And Interfacing", 
    "type": "Lecture",
    "location": "L-6",
    "day": "Monday",
    "start_time": "16:30:00",
    "end_time": "17:25:00",
    "teacher": "Dr Mohit Dua",
    "branch": "CS",
    "section": "A",
    "subsection": 4
}

###

DELETE  http://localhost:3000/timetable/63cecc5b89350bbaab7369b5

###

PATCH  http://localhost:3000/timetable/63cd3f1c36726c244b861174
Content-Type: application/json

{
    "name" : "garvit"
}
