GET http://localhost:3000/timetable

###

GET http://localhost:3000/timetable/Tuesday/CS/A/1

###

GET http://localhost:3000/timetable/Monday

###

POST http://localhost:3000/timetable/
Content-Type: application/json

{
    "subject": "Microprocessor & Interfacing", 
    "type": "Lecture",
    "location": "L-2",
    "day": "Wednesday",
    "start_time": "16:30:00",
    "end_time": "17:25:00",
    "teacher": "Dr Mohit Dua",
    "branch": "CS",
    "section": "A",
    "subsection": 4
}

###

DELETE  http://localhost:3000/timetable/63cf63ac604073bc496dd2a3

###

PATCH  http://localhost:3000/timetable/63cd3f1c36726c244b861174
Content-Type: application/json

{
    "subject": "Microprocessor & Interfacing", 
    "type": "Lecture",
    "location": "L-2",
    "day": "Wednesday",
    "start_time": "16:30:00",
    "end_time": "17:25:00",
    "teacher": "Dr Mohit Dua",
    "branch": "CS",
    "section": "A",
    "subsection": 4
}

### TEACHER'S ROUTES AHEAD

GET http://localhost:3000/teacherdb

### CLUB'S ROUTES AHEAD

GET http://localhost:3000/clubdb
